cd /opt/simple-cicd-app

cat > docker-compose.yml <<'EOF'
services:
  backend:
    image: ghcr.io/jokestevens/simple-ci-cd-web-app-backend:latest
    container_name: backend
    restart: unless-stopped

  frontend:
    image: ghcr.io/jokestevens/simple-ci-cd-web-app-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
EOF
