services:
  frontend:
    image: ghcr.io/${GHCR_OWNER}/${GHCR_REPO}-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/${GHCR_OWNER}/${GHCR_REPO}-backend:${IMAGE_TAG}
    environment:
      - APP_VERSION=${IMAGE_TAG}
    restart: unless-stopped
